[package]
name = "asmOS"
version = "0.1.0"
edition = "2021"
build = "recipes/build.rs"

[features]
x86_64 = ["kernel/x86_64"]
default = ["x86_64"]

[dependencies]
kernel = { path = "src/kernel" }

[workspace]
members = [
    "src/kernel",
]
